### ISSUE TITLE
Yocto Custom Applications Tree

### ISSUE THREAD

**Issue by ahmedrs1** [jku/poky#1]
I want to compile my applications with the following tree in yocto project:

 myapps/
├── Papps1
│   ├── module-apps1
│   │   └── app1
│   │       ├── include
│   │       │   ├── include files
│   │       ├── configure.ac
│   │       ├── Makefile
│   │       └── other source files
│   └── Papps2
│       └── app2
│          ├── include
│          ├── include files
│          ├── CMakeLists.txt
│          └── other source files
└── recipies_apps
    ├── recipies_app1.bb
    └── recipies_app2.bb
using bitbake to compile app1 i got the following error:
ERROR: Nothing PROVIDES 'app1'
is there any solution to compile this architecture tree in yocto ?

**Comment by jku** [comment]
this is my personal copy of poky, not a good place to file issues: sorry.

But on your question: _maybe_ it's possible but you'll be working against the system all the way. I would never suggest doing that: if you keep your code in separate repos things just work and you can follow tutorials and your recipes will look like everyone elses recipes...
